/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    this._$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (! this._$jscoverage) {
  this._$jscoverage = {};
}
if (! _$jscoverage['js/service/lang.js']) {
  _$jscoverage['js/service/lang.js'] = [];
  _$jscoverage['js/service/lang.js'][1] = 0;
  _$jscoverage['js/service/lang.js'][3] = 0;
  _$jscoverage['js/service/lang.js'][7] = 0;
  _$jscoverage['js/service/lang.js'][9] = 0;
  _$jscoverage['js/service/lang.js'][10] = 0;
  _$jscoverage['js/service/lang.js'][12] = 0;
  _$jscoverage['js/service/lang.js'][13] = 0;
  _$jscoverage['js/service/lang.js'][14] = 0;
  _$jscoverage['js/service/lang.js'][21] = 0;
}
_$jscoverage['js/service/lang.js'].source = ["<span class=\"k\">(</span><span class=\"k\">function</span> <span class=\"k\">(</span>win<span class=\"k\">)</span> <span class=\"k\">{</span>","","\t<span class=\"s\">\"use strict\"</span><span class=\"k\">;</span>","\t<span class=\"c\">/*global window */</span>","\t<span class=\"c\">/*global info */</span>","","\twin<span class=\"k\">.</span>lang <span class=\"k\">=</span> <span class=\"k\">{</span>","\t\tpush<span class=\"k\">:</span> <span class=\"k\">function</span><span class=\"k\">(</span>lang<span class=\"k\">)</span> <span class=\"k\">{</span>","\t\t\t<span class=\"k\">this</span><span class=\"k\">.</span>name <span class=\"k\">=</span> lang<span class=\"k\">;</span>","\t\t\t<span class=\"k\">var</span> obj <span class=\"k\">=</span> win<span class=\"k\">.</span>langs<span class=\"k\">[</span>lang<span class=\"k\">],</span>","\t\t\t\tkey<span class=\"k\">;</span>","\t\t\t<span class=\"k\">for</span> <span class=\"k\">(</span>key <span class=\"k\">in</span> obj<span class=\"k\">)</span> <span class=\"k\">{</span>","\t\t\t\t<span class=\"k\">if</span> <span class=\"k\">(</span>obj<span class=\"k\">.</span>hasOwnProperty<span class=\"k\">(</span>key<span class=\"k\">))</span> <span class=\"k\">{</span>","\t\t\t\t\t<span class=\"k\">this</span><span class=\"k\">[</span>key<span class=\"k\">]</span> <span class=\"k\">=</span> obj<span class=\"k\">[</span>key<span class=\"k\">];</span>","\t\t\t\t<span class=\"k\">}</span>","\t\t\t<span class=\"k\">}</span>","\t\t<span class=\"k\">}</span>","\t<span class=\"k\">}</span><span class=\"k\">;</span>","","\t<span class=\"c\">// default language</span>","\twin<span class=\"k\">.</span>lang<span class=\"k\">.</span>push<span class=\"k\">(</span>info<span class=\"k\">.</span>lang<span class=\"k\">);</span>","","<span class=\"k\">}</span><span class=\"k\">(</span>window<span class=\"k\">));</span>"];
_$jscoverage['js/service/lang.js'][1]++;
(function (win) {
  _$jscoverage['js/service/lang.js'][3]++;
  "use strict";
  _$jscoverage['js/service/lang.js'][7]++;
  win.lang = {push: (function (lang) {
  _$jscoverage['js/service/lang.js'][9]++;
  this.name = lang;
  _$jscoverage['js/service/lang.js'][10]++;
  var obj = win.langs[lang], key;
  _$jscoverage['js/service/lang.js'][12]++;
  for (key in obj) {
    _$jscoverage['js/service/lang.js'][13]++;
    if (obj.hasOwnProperty(key)) {
      _$jscoverage['js/service/lang.js'][14]++;
      this[key] = obj[key];
    }
}
})};
  _$jscoverage['js/service/lang.js'][21]++;
  win.lang.push(info.lang);
})(window);
