/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    this._$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (! this._$jscoverage) {
  this._$jscoverage = {};
}
if (! _$jscoverage['js/lang/en.js']) {
  _$jscoverage['js/lang/en.js'] = [];
  _$jscoverage['js/lang/en.js'][1] = 0;
  _$jscoverage['js/lang/en.js'][3] = 0;
  _$jscoverage['js/lang/en.js'][6] = 0;
  _$jscoverage['js/lang/en.js'][8] = 0;
}
_$jscoverage['js/lang/en.js'].source = ["<span class=\"k\">(</span><span class=\"k\">function</span> <span class=\"k\">(</span>win<span class=\"k\">)</span> <span class=\"k\">{</span>","","\t<span class=\"s\">\"use strict\"</span><span class=\"k\">;</span>","\t<span class=\"c\">/*global window */</span>","","\twin<span class=\"k\">.</span>langs <span class=\"k\">=</span> win<span class=\"k\">.</span>langs <span class=\"k\">||</span> <span class=\"k\">{}</span><span class=\"k\">;</span>","","\twin<span class=\"k\">.</span>langs<span class=\"k\">.</span>en <span class=\"k\">=</span> <span class=\"k\">{</span>","\t\tlanguage<span class=\"k\">:</span> <span class=\"s\">'language'</span><span class=\"k\">,</span>","\t\tlanguageName<span class=\"k\">:</span> <span class=\"s\">'english'</span>","\t<span class=\"k\">}</span><span class=\"k\">;</span>","","<span class=\"k\">}</span><span class=\"k\">(</span>window<span class=\"k\">));</span>"];
_$jscoverage['js/lang/en.js'][1]++;
(function (win) {
  _$jscoverage['js/lang/en.js'][3]++;
  "use strict";
  _$jscoverage['js/lang/en.js'][6]++;
  win.langs = (win.langs || {});
  _$jscoverage['js/lang/en.js'][8]++;
  win.langs.en = {language: "language", languageName: "english"};
})(window);
